//
// Action.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Action: Codable {

    public enum ModelType: String, Codable {
        case link = "link"
    }
    /** action button name */
    public var name: String
    /** fix value: link */
    public var type: ModelType
    /** action url */
    public var url: String

    public init(name: String, type: ModelType, url: String) {
        self.name = name
        self.type = type
        self.url = url
    }


}

