//
// MessagePushResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct MessagePushResponse: Codable {

    public var messageId: Int64

    public init(messageId: Int64) {
        self.messageId = messageId
    }


}

