//
// MessageObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct MessageObject: Codable {

    /** action size range is 0,3 */
    public var actions: [Action]?
    public var channelName: String
    public var content: String
    public var createdAt: String
    public var id: Int64
    public var title: String

    public init(actions: [Action]?, channelName: String, content: String, createdAt: String, id: Int64, title: String) {
        self.actions = actions
        self.channelName = channelName
        self.content = content
        self.createdAt = createdAt
        self.id = id
        self.title = title
    }


}

