//
// MessagePushRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct MessagePushRequest: Codable {

    /** action size range is 0,3 */
    public var actions: [Action]?
    /** message content */
    public var content: String
    /** when value is false, will not send client push */
    public var needPush: Bool
    /** message title */
    public var title: String

    public init(actions: [Action]?, content: String, needPush: Bool, title: String) {
        self.actions = actions
        self.content = content
        self.needPush = needPush
        self.title = title
    }


}

