//
// PageResponseOfMessageObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct PageResponseOfMessageObject: Codable {

    public var content: [MessageObject]?
    public var totalElements: Int64?
    public var totalPages: Int64?

    public init(content: [MessageObject]?, totalElements: Int64?, totalPages: Int64?) {
        self.content = content
        self.totalElements = totalElements
        self.totalPages = totalPages
    }


}

