//
// ResultOfMessageObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct ResultOfMessageObject: Codable {

    public var code: Int
    public var data: MessageObject?
    public var errmsg: String

    public init(code: Int, data: MessageObject?, errmsg: String) {
        self.code = code
        self.data = data
        self.errmsg = errmsg
    }


}

