//
// ResultOfMessagePushResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct ResultOfMessagePushResponse: Codable {

    public var code: Int
    public var data: MessagePushResponse?
    public var errmsg: String

    public init(code: Int, data: MessagePushResponse?, errmsg: String) {
        self.code = code
        self.data = data
        self.errmsg = errmsg
    }


}

